### ISSUE TITLE
About exam.csv in CODE-15% cohort

### ISSUE THREAD

**Issue by gunahn** [antonior92/ecg-age-prediction#2]
Hi, thank you for sharing the amazing research!

I tried to reproduce the result of fig 2 (Adjusted survival curves) in paper with exam.csv in CODE-15% cohort (https://zenodo.org/record/4916206#.Yib1gRPP30o)

I calculated "diff" columns by 

```
total_data = pd.read_csv('exams_CODE15.csv')
total_data['diff'] = total_data['nn_predicted_age'] - total_data['age']
```

And I separate the dataset into 3 groups as i1, i2, and i3. I1 was the group that nn_predicted_age is 8 years greater than age, I2 was the one that nn_predicted_age is 8 years smaller than age, I3 was the one within a range of 8 years from their age 

  ```
  from lifelines import KaplanMeierFitter
  i1 = (total_data['diff'] > 8)      
  i2 = (total_data['diff'] < -8)
  
  i3 = i1+i2
  i3 = ~i3
   
  durations = total_data['timey']
  event_observed = total_data['death'].astype('int')
  kmf_old = KaplanMeierFitter() 
  kmf_young = KaplanMeierFitter() 
  
  kmf = KaplanMeierFitter() 
  
  kmf_old.fit(durations[i1], event_observed[i1],label='ECG_age_Old_abs')
  a1 = kmf_old.plot()
  
  kmf_young.fit(durations[i2], event_observed[i2],label='ECG_age_Young_abs')
  a2 = kmf_young.plot()
  
  kmf.fit(durations[i3], event_observed[i3],label='ECG_age_similar_abs')
  
  kmf.plot(ax=a1) 
```
 However, the result that I got from the above code is opposite from your result of the paper. 

![image](https://user-images.githubusercontent.com/58503653/157179827-d4691684-66f4-467b-aa12-617ca2617263.png)

Can you check the exam.csv in CODE-15% cohort has all right value? 

Thank you for reading
Best Regards, 
Gun Ahn

**Comment by antonior92** [comment]
Great question!

The curve in the paper is adjusted by age and sex. As one example with the adjusted effects:
``` 
import pandas as pd
import numpy as np
from lifelines import CoxPHFitter

data = pd.read_csv('exams.csv')
data['diff'] = total_data['nn_predicted_age'] - total_data['age']

df = data.loc[:, ['diff', 'age', 'is_male', 'timey', 'death']]
df = df.dropna()
cph = CoxPHFitter()
cph.fit(df, duration_col='timey', event_col='death')

cph.plot_partial_effects_on_outcome(covariates='diff', values=[-8, 0, 8])
``` 

![Screenshot 2022-03-08 at 09 09 04](https://user-images.githubusercontent.com/16557411/157194042-472a928b-a366-49d7-a1a7-2e1987a7e5ae.png)
Notebook: https://colab.research.google.com/drive/1jEC2ID1lfN1iF5_yZ2VzftQI0vkIZ_AH?usp=sharing


This is not really the script we used in the paper. There are some differences still, since in the paper what was used was the entire interval.... Anyway, I hope it illustrates the effect of adjusting by age and sex...


About the reason for adjusting for age and sex. Is that both of these variables are very good predictors of mortality and as you can see in the leftmost plot here:
![predicted](https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-021-25351-7/MediaObjects/41467_2021_25351_Fig1_HTML.png?as=webp)
The difference between ecg-age and age is strongly correlated with the age. 


Moreover, young people tend to have larger values of `diff` than older people (see how in the leftmost plot the curve deviates from the diagonal). This explains why the results appear inverted without the adjustment.
